name: cli_tools
version: 0.5.0-beta.1
description: A collection of tools for building great command-line interfaces.
repository: https://github.com/serverpod/cli_tools
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/cli_tools/issues

topics:
  - cli
  - tools
  - command-line
  - dart

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.7.0
  ci: ^0.1.0
  collection: ^1.18.0
  http: '>=0.13.0 <2.0.0'
  meta: ^1.16.0
  path: ^1.8.2
  pub_api_client: '>=2.4.0 <4.0.0'
  pub_semver: ^2.1.4
  rfc_6901: ^0.2.0
  super_string: ^1.0.3
  yaml_codec: ^1.0.0

dev_dependencies:
  test: ^1.24.0
  serverpod_lints: '>=1.2.6'
  test_descriptor: ^2.0.2
